-- Update city region codes and names
UPDATE zip_cities SET region_code = 1, region_name = 'Республика Адыгея' WHERE name = 'Майкоп';
UPDATE zip_cities SET region_code = 2, region_name = 'Республика Башкортостан' WHERE name = 'Уфа';
UPDATE zip_cities SET region_code = 2, region_name = 'Республика Башкортостан' WHERE name = 'Стерлитамак';
UPDATE zip_cities SET region_code = 2, region_name = 'Республика Башкортостан' WHERE name = 'Нефтекамск';
UPDATE zip_cities SET region_code = 3, region_name = 'Республика Бурятия' WHERE name = 'Улан-Удэ';
UPDATE zip_cities SET region_code = 11, region_name = 'Республика Коми' WHERE name = 'Ухта';
UPDATE zip_cities SET region_code = 12, region_name = 'Республика Марий Эл' WHERE name = 'Йошкар-Ола';
UPDATE zip_cities SET region_code = 13, region_name = 'Республика Мордовия' WHERE name = 'Саранск';
UPDATE zip_cities SET region_code = 15, region_name = 'Республика Северная Осетия - Алания' WHERE name = 'Владикавказ';
UPDATE zip_cities SET region_code = 16, region_name = 'Республика Татарстан' WHERE name = 'Казань';
UPDATE zip_cities SET region_code = 16, region_name = 'Республика Татарстан' WHERE name = 'Набережные Челны';
UPDATE zip_cities SET region_code = 19, region_name = 'Республика Хакасия' WHERE name = 'Абакан';
UPDATE zip_cities SET region_code = 21, region_name = 'Чувашская Республика' WHERE name = 'Чебоксары';
UPDATE zip_cities SET region_code = 22, region_name = 'Алтайский край' WHERE name = 'Барнаул';
UPDATE zip_cities SET region_code = 22, region_name = 'Алтайский край' WHERE name = 'Рубцовск';
UPDATE zip_cities SET region_code = 23, region_name = 'Краснодарский край' WHERE name = 'Краснодар';
UPDATE zip_cities SET region_code = 23, region_name = 'Краснодарский край' WHERE name = 'Сочи';
UPDATE zip_cities SET region_code = 23, region_name = 'Краснодарский край' WHERE name = 'Адлер';
UPDATE zip_cities SET region_code = 23, region_name = 'Краснодарский край' WHERE name = 'Новороссийск';
UPDATE zip_cities SET region_code = 26, region_name = 'Ставропольский край' WHERE name = 'Ставрополь';
UPDATE zip_cities SET region_code = 27, region_name = 'Хабаровский край' WHERE name = 'Комсомольск-на-Амуре';
UPDATE zip_cities SET region_code = 30, region_name = 'Астраханская область' WHERE name = 'Астрахань';
UPDATE zip_cities SET region_code = 31, region_name = 'Белгородская область' WHERE name = 'Белгород';
UPDATE zip_cities SET region_code = 31, region_name = 'Белгородская область' WHERE name = 'Старый Оскол';
UPDATE zip_cities SET region_code = 32, region_name = 'Брянская область' WHERE name = 'Брянск';
UPDATE zip_cities SET region_code = 34, region_name = 'Волгоградская область' WHERE name = 'Волгоград';
UPDATE zip_cities SET region_code = 35, region_name = 'Вологодская область' WHERE name = 'Вологда';
UPDATE zip_cities SET region_code = 35, region_name = 'Вологодская область' WHERE name = 'Череповец';
UPDATE zip_cities SET region_code = 36, region_name = 'Воронежская область' WHERE name = 'Россошь';
UPDATE zip_cities SET region_code = 37, region_name = 'Ивановская область' WHERE name = 'Иваново';
UPDATE zip_cities SET region_code = 38, region_name = 'Иркутская область' WHERE name = 'Иркутск';
UPDATE zip_cities SET region_code = 39, region_name = 'Калининградская область' WHERE name = 'Калининград';
UPDATE zip_cities SET region_code = 43, region_name = 'Кировская область' WHERE name = 'Киров';
UPDATE zip_cities SET region_code = 46, region_name = 'Курская область' WHERE name = 'Курск';
UPDATE zip_cities SET region_code = 48, region_name = 'Липецкая область' WHERE name = 'Липецк';
UPDATE zip_cities SET region_code = 50, region_name = 'Московская область' WHERE name = 'Подольск';
UPDATE zip_cities SET region_code = 51, region_name = 'Мурманская область' WHERE name = 'Мурманск';
UPDATE zip_cities SET region_code = 56, region_name = 'Оренбургская область' WHERE name = 'Оренбург';
UPDATE zip_cities SET region_code = 56, region_name = 'Оренбургская область' WHERE name = 'Орск';
UPDATE zip_cities SET region_code = 58, region_name = 'Пензенская область' WHERE name = 'Пенза';
UPDATE zip_cities SET region_code = 59, region_name = 'Пермский край' WHERE name = 'Пермь';
UPDATE zip_cities SET region_code = 60, region_name = 'Псковская область' WHERE name = 'Псков';
UPDATE zip_cities SET region_code = 61, region_name = 'Ростовская область' WHERE name = 'Ростов-на-Дону';
UPDATE zip_cities SET region_code = 61, region_name = 'Ростовская область' WHERE name = 'Волгодонск';
UPDATE zip_cities SET region_code = 61, region_name = 'Ростовская область' WHERE name = 'Каменск-Шахтинский';
UPDATE zip_cities SET region_code = 61, region_name = 'Ростовская область' WHERE name = 'Азов';
UPDATE zip_cities SET region_code = 62, region_name = 'Рязанская область' WHERE name = 'Рязань';
UPDATE zip_cities SET region_code = 63, region_name = 'Самарская область' WHERE name = 'Самара';
UPDATE zip_cities SET region_code = 64, region_name = 'Саратовская область' WHERE name = 'Саратов';
UPDATE zip_cities SET region_code = 66, region_name = 'Свердловская область' WHERE name = 'Екатеринбург';
UPDATE zip_cities SET region_code = 66, region_name = 'Свердловская область' WHERE name = 'Лесной';
UPDATE zip_cities SET region_code = 67, region_name = 'Смоленская область' WHERE name = 'Смоленск';
UPDATE zip_cities SET region_code = 68, region_name = 'Тамбовская область' WHERE name = 'Тамбов';
UPDATE zip_cities SET region_code = 69, region_name = 'Тверская область' WHERE name = 'Тверь';
UPDATE zip_cities SET region_code = 71, region_name = 'Тульская область' WHERE name = 'Тула';
UPDATE zip_cities SET region_code = 72, region_name = 'Тюменская область' WHERE name = 'Тюмень';
UPDATE zip_cities SET region_code = 73, region_name = 'Ульяновская область' WHERE name = 'Ульяновск';
UPDATE zip_cities SET region_code = 76, region_name = 'Ярославская область' WHERE name = 'Ярославль';
UPDATE zip_cities SET region_code = 77, region_name = 'г. Москва' WHERE name = 'Москва';
UPDATE zip_cities SET region_code = 78, region_name = 'г. Санкт-Петербург' WHERE name = 'Санкт-Петербург';
UPDATE zip_cities SET region_code = 89, region_name = 'Ямало-Ненецкий автономный округ' WHERE name = 'Ноябрьск';